apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terroir-tracking-web
  description: Find where your juice comes from
spec:
  type: website
  lifecycle: production
  owner: tracking-team

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terroir-website
spec:
  type: website
  lifecycle: production
  owner: tracking-team